### ISSUE TITLE
looking forward to the code and dataset

### ISSUE THREAD

**Issue by GilgameshD** [krrish94/shapeAdjustment#1]

**Comment by yangggzhang** [comment]
looking forward to the code and dataset

**Comment by ndrplz** [comment]
+1

**Comment by ndrplz** [comment]
Might I add that it's ridicolous that a paper accepted to a top conference such as ICRA does not release the dataset as promised in the paper?

**Comment by Haotian-Zhang** [comment]
Hi @krrish94 , I wonder if the codes can be released these days?

**Comment by krrish94** [comment]
Hi!

Due to a few contractual obligations, I couldn't release the code up until now. I know it's been over a year and a half, but better late than never.

We released an abridged, heavily simplified, but just as efficient version of our code here.
https://github.com/krrish94/ICRA2017

Hope this helps.

Cheers!
